### ISSUE TITLE
city(市区町村)でエラーになる場合がある。

### ISSUE THREAD

**Issue by hwakimoto** [sankichi92/shikuchoson-hazardmap-template#31]
hazardmap-config.jsonc に特定のCityの指定を行うと、CIがエラーになり、OSM Relation not found.となることがある。

ex：埼玉県比企郡小川町

NG "city": "比企郡小川町",
NG "city": "比企郡",
OK "city": "小川町",

つまり郡を無視することで成功する。

**Comment by sankichi92** [comment]
related https://github.com/sankichi92/shikuchoson-hazardmap-template/issues/26

**Comment by sankichi92** [comment]
## Social Hack Day 36 議論メモ

with @hwakimoto 

### 課題

https://github.com/sankichi92/shikuchoson-hazardmap-template/blob/22eacdb3b1328539bef57a4d87be9c1cb8d75115/scripts/fetch-city-osm.js#L18

fetch-city-osm.js の上記の箇所が問題。

- 比企郡は admin_level が 6
  - https://www.openstreetmap.org/relation/1769300
- 上京区は admin_level が 8
  - https://www.openstreetmap.org/relation/357817

そのため、比企郡や上京区は現在のクエリでは取得できない。

また、「比企郡小川町」や「京都市上京区」は完全一致する地物(?)が OSM にないため、引っかからない。
組み合わせずに「比企郡」「小川町」「京都市」「上京区」といった単位でクエリする必要がある。

### 解決案

- admin_level の指定をなくす
  - もともと想定外の事態をなくすために導入していたが、むしろこれが問題になっているので必要なさそう
- 「比企郡小川町」や「京都市上京区」といった入力そのものに対応するのではなく、ドキュメントでカバーする
  - 直感としては上記を入力したくなるが、パース等で対応するのが困難なため

**Comment by sankichi92** [comment]
https://github.com/sankichi92/shikuchoson-hazardmap-template/issues/20 で OpenStreetMap の Overpass API ではなく、https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-v3_0.html から作成した https://github.com/sankichi92/shikuchoson-boundaries を使用するようにしました。
これにより設定項目も以下のように少し厳密になったので、こちらクローズします。
https://github.com/sankichi92/shikuchoson-hazardmap-template/blob/23d2b7201d199421e9b78e739d323b7526de3d76/hazardmap-config.jsonc#L2-L13
