### ISSUE TITLE
CSV で追加したレイヤのうち8番目のマーカーアイコンが表示されない

### ISSUE THREAD

**Issue by momosaic** [sankichi92/shikuchoson-hazardmap-template#43]
CSVに追加したアイコンですが、9個までは色別で表示されましたが、10個目以降が以下のようになりました。使用できるアイコン数が多いと、情報を細分化して伝えやすくなるので、10個目以降もアイコンが表示されるとありがたいです。
![image](https://user-images.githubusercontent.com/96829524/187194190-de82a568-9fae-4539-b99b-3cacf88bbbbf.png)

**Comment by sankichi92** [comment]
Issue 作成ありがとうございます。
問題が起きているのは https://github.com/hachioji-city/hachioji-hazardmap/tree/b40998b21963089a32c3c612df7a8b57f8b9d3c2 ですかね。

現象を確認したところ、10個目からおかしくなるというわけではなく、8個目の CSV レイヤのアイコン画像がスクショのように表示されないようでした。

なお、アイコン画像は https://github.com/pointhi/leaflet-color-markers を用いており、色の種類が9色しかありません。
そのため、10個目からは色をローテーションして1個目と同じ色が使用される仕様に現状なっています。

8番目には本来 `grey` が使用されるはずなのですが、コードを確認したところ、
https://github.com/sankichi92/shikuchoson-hazardmap-template/blob/141ce059a2acf1a6453ec0b116876a73cfa3729c/src/components/OverlayFeatureLayers.tsx#L21
と `gray` で `e` と `a` が違っていました……。
調べてみたところ、スペルミスというよりは、アメリカ英語とイギリス英語の違いのようです。

テンプレートに関してはこれから修正します。

**Comment by sankichi92** [comment]
27e4a681889b4026aade7965675e9a0ced740850 で修正しました。
