### ISSUE TITLE
GitHub Actionsの権限設定について

### ISSUE THREAD

**Issue by tmatsuno** [sankichi92/shikuchoson-hazardmap-template#58]
readme.meにGitHub Actionsの設定について、
テンプレートから新しく作成した際に、GITHUB_TOKENの権限がデフォルトではReadonlyのため、
これをアクセス権限の追加設定が必要となる。
GitHubの利用に慣れていないシビックテックの人によっては、この部分で設定反映のビルドが出来ずFailすることで、
躓いてしまい、利用に至らないケースが想定されるため、この設定変更についてreadme.mdで触れておくと良さそう。

**Comment by tmatsuno** [comment]
なお、 #57 の改修後の初回デプロイでデプロイ失敗を確認。
Settingsでの設定変更が必要な模様。
<img width="885" alt="スクリーンショット 2023-01-31 17 03 14" src="https://user-images.githubusercontent.com/1682239/215701675-6b572515-5e26-4437-837e-e377461b3521.png">

**Comment by sankichi92** [comment]
README の「使い方 > ハザードマップの作成・公開」の手順 1 〜 3 を実施いただきましたか？
https://github.com/sankichi92/shikuchoson-hazardmap-template#ハザードマップの作成公開
手順2を実施したあと、手順3のコミットで起動するワークフローでデプロイ成功するかと思うのですが。

**Comment by sankichi92** [comment]
テンプレートから適当なリポジトリをつくって「使い方 > ハザードマップの作成・公開」の手順 1 〜 3 を実施しましたが、再現しませんでした。ご確認お願いします。
（手順 1 の時点で失敗してしまうのはいまのところ解決策がなく、仕方ないかなと思っています。）

**Comment by tmatsuno** [comment]
再度作成し直してテストしたところ、Pageも更新されつつ動作した事を確認しました。
ActionsからPushしないでActionsで生成されたものがそのままPageにできるようになったのですね。
